proxies:
  - id: 0
    localAddr: ":20000"
    remoteAddr: "btc.f2pool.com:1314"
    user: "zcy"
    date: "2022-2-22"

  - id: 1
    localAddr: ":20001"
    remoteAddr: "eth.f2pool.com:6688"
    user: "xu"
    date: "2022-2-22"

  - id: 2
    localAddr: ":20003"
    remoteAddr: "localhost:10809"
    user: "v2ray"
    date: "2022-2-22"

log: "./gredir.log"